//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGameConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardGameConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///					 Thank you for playing!
        ///				---------------------------------------
        ///
        ///					  Developed by Asel S.
        ///
        ///
        ///.
        /// </summary>
        internal static string ExitMenuContent {
            get {
                return ResourceManager.GetString("ExitMenuContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	
        ///	
        ///			╔════════════════════════════════════════════════════════════════╗
        ///			║                                                                ║
        ///			║           ██████╗  ██████╗ ██╗  ██╗███████╗██████╗             ║
        ///			║           ██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗            ║
        ///			║           ██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝            ║
        ///			║           ██╔═══╝ ██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗            ║
        ///			║           ██║     ╚██████╔╝██║  ██╗███████╗██║  ██║            ║
        ///			║      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainMenuContent {
            get {
                return ResourceManager.GetString("MainMenuContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///			╔════════════════════════════════════════════════════════════════╗
        ///			║                         Betting Rounds                         ║
        ///			║                     ----------------------                     ║
        ///			║  There are two betting rounds.                                 ║
        ///			║                                                                ║
        ///			║  The first betting round starts after each player has anteed   ║
        ///			║  up. After the first betting round, each player has the chance ║
        ///			║  to mu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TutorialBettingContent {
            get {
                return ResourceManager.GetString("TutorialBettingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	
        ///			╔════════════════════════════════════════════════════════════════╗
        ///			║                          Poker Hands                           ║
        ///			║                     ----------------------                     ║
        ///			║  The following poker hands are listed in order of most value:  ║           
        ///			║   Royal Flush - Ace, King, Queen, Jack, 10, all the same suit  ║
        ///			║   Straight Flush - Five cards in a sequence, all the same suit ║
        ///			║   Four of a kind - All four cards of the same rank.            ║        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TutorialHandsContent {
            get {
                return ResourceManager.GetString("TutorialHandsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///                        ╔════════════════════════════════════════════════════════════════╗
        ///                        ║                          Introduction                          ║
        ///                        ║                     ----------------------                     ║
        ///                        ║  This game is a simplified variant of five card draw.          ║          
        ///                        ║                                                                ║
        ///                        ║  Each player [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TutorialIntroductionContent {
            get {
                return ResourceManager.GetString("TutorialIntroductionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///			╔════════════════════════════════════════════════════════════════╗
        ///			║                           Showdown                             ║
        ///			║                     ----------------------                     ║
        ///			║  During showdown, players left in the game reveal and compare  ║    
        ///			║  their hands to determine a winner.                            ║
        ///			║                                                                ║
        ///			║  The player with the most valuable poker hand takes the pot    ║
        ///			║  a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TutorialShowdownContent {
            get {
                return ResourceManager.GetString("TutorialShowdownContent", resourceCulture);
            }
        }
    }
}
